import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
const recipes = [
  {
    name: "Falafel Wrap",
    ingredients: [
      "Falafel",
      "Lettuce",
      "Tomato",
      "Pita",
      "Onion",
      "Hummus",
      "Parsley",
      "Mayo",
    ],
  },
  {
    name: "Spaghetti",
    ingredients: [
      "Spaghetti",
      "Tomato Sauce",
      "Meatballs",
      "Onion",
      "Parmesean",
    ],
  },
  {
    name: "Black Bean Burger",
    ingredients: [
      "Black Bean Burger",
      "Lettuce",
      "Tomato",
      "Onion",
      "Buns",
      "Mayo",
      "Cheese",
      "Fries",
    ],
  },
  {
    name: "Pizza",
    ingredients: [
      "Dough",
      "Tomato Sauce",
      "Cheese",
      "Olives",
      "Basil",
      "Garlic",
    ],
  },
  {
    name: "Chicken Ceasar Salad",
    ingredients: [
      "Chicken",
      "Ceasar Dressing",
      "Lettuce",
      "Tomato",
      "Parmesean",
      "Pita Chips",
    ],
  },
  {
    name: "Pad Thai",
    ingredients: [
      "Pad Thai Sauce",
      "Rice Noodles",
      "Tofu",
      "Peanuts",
      "Peanut Butter",
      "Carrots",
      "Broccoli",
      "Lime",
      "Cilantro",
      "Sesame Oil",
    ],
  },
  {
    name: "Nachos",
    ingredients: [
      "Nachos",
      "Cheese",
      "Tomato",
      "Lettuce",
      "Onion",
      "Meat",
      "Salsa",
      "Avacado",
      "Tex-Mex Seasoning",
      "Cilantro",
    ],
  },
  {
    name: "Breakfast Sandwich",
    ingredients: ["Buns", "Egg", "Cheese", "Hashbrown", "Sausage"],
  },
  {
    name: "Fried Gnocchi",
    ingredients: ["Gnocchi", "Tomato Sauce", "Pesto", "Cheese"],
  },
  {
    name: "Smoothies",
    ingredients: ["Frozen Fruits", "Milk", "Juice", "Protien Powder"],
  },
  {
    name: "Fattoush Salad",
    ingredients: [
      "Lettuce",
      "Tomato",
      "Cucumber",
      "Green Pepper",
      "Onion",
      "Green Onion",
      "Parsley",
      "Pita Chips",
      "Dressing",
    ],
  },
  {
    name: "Sandwhiches",
    ingredients: ["Buns", "Meat", "Cheese", "Lettuce", "Mayo"],
  },
  { name: "Fried Tofu and Veggies", ingredients: ["Tofu", "Veggies"] },
  {
    name: "Fresh Rolls",
    ingredients: [
      "Rice Paper",
      "Lettuce",
      "Rice Noodles",
      "Avacado",
      "Soy Sauce",
      "Cilantro",
      "Peanut Butter",
    ],
  },
  {
    name: "Overnight Oats",
    ingredients: ["Oats", "Milk", "Blueberries", "Chocolate Chips"],
  },
];

export default function Home() {
  const [selectedRecipes, setSelectedRecipes] = useState([]);
  const toggleRecipe = (recipe) => {
    if (selectedRecipes.includes(recipe)) {
      setSelectedRecipes(
        selectedRecipes.filter(function (r) {
          return r !== recipe;
        })
      );
    } else {
      setSelectedRecipes([...selectedRecipes, recipe]);
    }
  };

  const getIngredients = () => {
    let ingredients = [];
    selectedRecipes.forEach((recipe) => {
      recipe.ingredients.forEach((ing) => {
        if (!ingredients.includes(ing)) {
          ingredients.push(ing);
        }
      });
    });
    console.log(ingredients);
    return ingredients;
  };

  return (
    <div className={styles.container}>
      {console.log(selectedRecipes)}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Shopping List Generator</h1>
        {recipes.map((recipe) => (
          <>
            <label>
              <input
                key={recipe.name}
                type="checkbox"
                checked={selectedRecipes.includes(recipe)}
                onChange={() => toggleRecipe(recipe)}
              />
              {recipe.name}
            </label>
          </>
        ))}
        {getIngredients().map((ingredent) => (
          <li key={ingredent}>{ingredent}</li>
        ))}
      </main>
    </div>
  );
}
